name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on:
      group: OpenStack
      labels: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run Docker Container
        env:
          NEXT_PUBLIC_GOOGLE_API_KEY: "${{ secrets.NEXT_PUBLIC_GOOGLE_API_KEY }}"
        run: |
          docker compose -f prod.compose.yml up -d --build
